block:
  diamond-gemstone:
    # Optional: displayName: "&aItem {type}"
    head: "basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2I5NDJiOWYzODY4MWJmOTZjODRkMTgxYmFkOWVmMGFjYzA0NzYzNWQyNTRlMzQ4OWZjODExODg2NzgxY2E1ZCJ9fX0="
messages:
  usage:
    - "/itsmyblock reload: Reloads the configuration"
    - "/itsmyblock give <player> <type>: Gives a block to the given player"
  reload: "&aConfiguration reloaded!"
  typeDoesntExist: "&cThis block type doesn't exist!"
  inventoryFull: "&cThe player's inventory is full!"
  success: "&aSuccess!"